[package]
name = "server"
version = "0.1.0"
authors = ["Noituri"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
serde_derive = "1.0.89"
serde = "1.0.89"
base64 = "0.10.1"
config = "0.9.2"
mongodb = "0.3.12"
